apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ service_name }}
  template:
    metadata:
      labels:
        app: {{ service_name }}
    spec:
      containers:
      - name: {{ service_name }}
        image: {{ image }}
        ports:
        {% for port in ports %}
        - containerPort: {{ port }}
        {% endfor %}
